services:
  - type: web
    name: mongodb
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
    ports:
      - port: 27017
        protocol: tcp
