services:
  - type: pserv
    name: mongodb
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: rootUser
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: rootPassword123
    healthCheckPath: ""  # <–– this disables default HTTP health checks
